SHELL=/bin/sh
#
# This makefile was produced by /usr/bin/fmgen at 04:22:20 PM on 02/27/96
# If it is invoked by the command line
#	make -f makefile
# it will compile the fortran modules indicated by SRCS into the object
# modules indicated by OBJS and produce an executable named a.out.
#
# If it is invoked by the command line
#	make -f makefile a.out.prof
# it will compile the fortran modules indicated by SRCS into the object
# modules indicated by OBJS and produce an executable which profiles
# named a.out.prof.
#
# To remove all the objects but leave the executables use the command line
#	make -f makefile clean
#
# To remove everything but the source files use the command line
#	make -f makefile clobber
#
# To remove the source files created by /usr/bin/fmgen and this makefile
# use the command line
#	make -f makefile void
#
# The parameters SRCS and OBJS should not need to be changed.  If, however,
# you need to add a new module add the name of the source module to the
# SRCS parameter and add the name of the resulting object file to the OBJS
# parameter.  The new modules are not limited to fortran, but may be C, YACC,
# LEX, or CAL.  An explicit rule will need to be added for PASCAL modules.
#
SRCS=ra2grib2.f u135.f chkgrid.f rdsect1.f rdsect3.f rdsect4.f rdsect5.f rdtdlpk.f packgrib2.f chkdup.f chkgrid4.f gribclose.f 

OBJS=ra2grib2.o u135.o chkgrid.o rdsect1.o rdsect3.o rdsect4.o rdsect5.o rdtdlpk.o packgrib2.o chkdup.o chkgrid4.o gribclose.o 
#
# Tunable parameters
#
# CF		Name of the fortran compiling system to use
# LDFLAGS	Flags to the loader
# LIBS		List of libraries
# CMD		Name of the executable
# PROFLIB	Library needed for profiling
#
CF =	   ncepxlf90
FC =	   ncepxlf90
#LDFLAGS =  /nwpara/lib/libmdl_4.a -L/nwprod/lib -lg2_4 -lw3_4 -lbacio_4 \
LDFLAGS =  -L/nwprod/lib -lg2_4 -lw3_4 -lmdl_4 -lbacio_4 \
           -L/usrx/local/64bit/lib -ljasper -lpng -lz
CMD  =       mdl_ra2grib2
PROFLIB =	
#
# To perform the default compilation, use the first line
# To compile with flowtracing turned on, use the second line
# To compile giving profile additonal information, use the third line
# WARNING:  SIMULTANEOUSLY PROFILING AND FLOWTRACING IS NOT RECOMMENDED 
FFLAGS = -qfixed -qintlog -O3 -qstrict -qintsize=4 -qrealsize=4 -qzerosize

# Lines from here on down should not need to be changed.  They are the
# actual rules which make uses to build a.out.
#
all:		$(CMD)

$(CMD):		$(OBJS)
	$(CF) $(LDFLAGS) -o $(@) $(OBJS) $(LIBS)

# Make the profiled version of the command and call it a.out.prof
#
$(CMD).prof:	$(OBJS)
	$(CF) $(LDFLAGS) -o $(@) $(OBJS) $(PROFLIB) $(LIBS)

clean:
	-rm -f $(OBJS)

clobber:	clean
	-rm -f $(CMD) $(CMD).prof

void:	clobber
	-rm -f $(SRCS) makefile
