      SUBROUTINE SETMIS(KFILDO,SDATA,NSTA,XMISSP,XMISSS)
C
C        NOVEMBER 1997   GLAHN   TDL   MOS-2000
C        DECEMBER 1998   GLAHN   ADDED  COMMENT ON CHECK FOR 9997
C
C        PURPOSE
C           TO SET THE VALUES OF XMISSP AND XMISSS TO 9999. AND 9997.,
C           RESPECTIVELY WHEN THOSE VALUES ACTUALLY OCCUR IN THE DATA
C           IN SDATA( ).  OTHERWISE, THE VALUES ARE SET TO 0.
C   
C        DATA SET USE
C            KFILDO - UNIT NUMBER OF OUTPUT (PRINT) FILE.  (OUTPUT)
C
C        VARIABLES
C              KFILDO = UNIT NUMBER OF OUTPUT (PRINT) FILE.  (INPUT)
C            SDATA(K) = DATA FOR PROCESSING (K=1,NSTA).  (INPUT)
C                NSTA = NUMBER OF VALUES IN SDATA( ).  TREATED AS ITS
C                       DIMENSION.  (INPUT)
C              XMISSP = PRIMARY MISSING VALUE RETURNED AS 9999 WHEN
C                       9999 OCCURS IN SDATA( ); 0 OTHERWISE.  (OUTPUT)
C              XMISSS = SECONDARY MISSING VALUE RETURNED AS 9997 WHEN
C                       9997 OCCURS IN SDATA( ); 0 OTHERWISE.  (OUTPUT)
C 
C        NONSYSTEM SUBROUINES USED 
C            NONE
C
      DIMENSION SDATA(NSTA)
C
      XMISSP=0.
      XMISSS=0.
C
C        CHECK FOR PRIMARY MISSING VALUE.
C
      DO 120 K=1,NSTA
C
      IF(SDATA(K).EQ.9999.)THEN
         XMISSP=9999.
         GO TO 130
      ENDIF
C
 120  CONTINUE
C
C        CHECK FOR SECONDARY MISSING VALUE.  NOTE THAT THIS CHECK
C        IS DONE EVEN WHEN A PRIMARY IS NOT FOUND.
C
 130  DO 140 K=1,NSTA
C
      IF(SDATA(K).EQ.9997.)THEN
C           IT IS ASSUMED THE VALUE IS EXACTLY 9997.
         XMISSP=9999.
         XMISSS=9997.
C           XMISSS CANNOT BE OTHER THAN ZERO UNLESS XMISSP IS ALSO.
         GO TO 150
      ENDIF
C
 140  CONTINUE
C
 150  RETURN
      END
