      SUBROUTINE TRDATA(KFILDO,AA,XDATA,N,NVRBL,NSTA)
C
C        DECEMBER 1997   GLAHN   TDL   MOS-2000
C
C        PURPOSE
C            TO TRANSFER DATA FROM A 2-DIMENSIONAL ARRAY TO
C            A 1-DIMENSIONAL ARRAY.  THIS IS USED PRIMARILY
C            WHEN THE DATA IN THE ARRAY ARE 2-D AND A
C            ROW OF DATA IS WANTED, BUT THE ARRAY IS
C            DIMENSIONED 1-D IN THE CALLING PROGRAM.
C   
C        DATA SET USE
C            KFILDO    - UNIT NUMBER OF OUTPUT (PRINT) FILE.  (OUTPUT)
C
C        VARIABLES
C              KFILDO = UNIT NUMBER OF OUTPUT (PRINT) FILE.  (INPUT)
C             AA(N,K) = ARRAY FROM WHICH TO TAKE DATA (N=1,NVRBL) 
C                       (K=1,NSTA).  (INPUT)
C            XDATA(K) = ARRAY TO PUT DATA INTO FOR VARIABLE N
C                       (K=1,NSTA).  (OUTPUT)
C                   N = ROW FROM WHICH TO TAKE DATA.  (INPUT)
C               NVRBL = FIRST DIMENSION OF AA( , ).  (INPUT)
C                NSTA = SECOND DIMENSION OF AA( , ) AND DIMENSION
C                       OF XDATA( ).  (INPUT)
C 
C        NONSYSTEM SUBROUINES USED 
C            NONE
C
      DIMENSION AA(NVRBL,NSTA)
      DIMENSION XDATA(NSTA)
C
      DO 120 K=1,NSTA
      XDATA(K)=AA(N,K)
 120  CONTINUE
C
      RETURN
      END
