      SUBROUTINE SCALX2(KFILDO,XDATA,DATA,NVAL,CONST,ADD,NSCALE,IER)
C 
C        AUGUST    2009   GLAHN   mDL   MOS-2000
C
C        PURPOSE
C            TO SCALE A VARIABLE X = (Y*CONST+ADD)*10.**NSCALE.
C            MISSINGS DESIGNATED BY 9999. ARE NOT MODIFIED.
C            THIS CAN BE USED FOR VECTOR OR GRIDDED DATA.
C   
C        DATA SET USE
C            KFILDO    - UNIT NUMBER OF OUTPUT (PRINT) FILE.  (OUTPUT)
C
C        VARIABLES
C              KFILDO = UNIT NUMBER OF OUTPUT (PRINT) FILE.  (INPUT)
C            XDATA(K) = THE DATA TO SCALE (K=1,NVAL).  (INPUT)
C             DATA(K) = THE SCALED DATA (K=1,NVAL).  (OUTPUT)
C               CONST = THE MULTIPLIER FOR SCALING.  (INPUT)
C                 ADD = ADDITIVE CONSTANT.  (INPUT)
C              NSCALE = THE POWER OF TEN FOR SCALING.  (INPUT)
C                NVAL = THE NUMBER OF VALUES IN XDATA( ) BEING DEALT
C                       WITH.  (INPUT)
C                 IER = ERROR RETURN.
C                       0 = GOOD RETURN.
C                       (OUTPUT)
C        1         2         3         4         5         6         7 X
C 
C        NONSYSTEM SUBROUTINES USED 
C            NONE
C
      DIMENSION XDATA(NVAL),DATA(NVAL)
C
      IER=0
C
D     WRITE(KFILDO,100)NVAL,NSCALE,CONST,ADD
D100  FORMAT(/' IN SCALX2 AT 100--NVAL,NSCALE,CONST,ADD',2I8,2F8.2)
C
      DO 120 K=1,NVAL
C
      IF(NINT(XDATA(K)).EQ.9999)THEN
         DATA(K)=9999.
      ELSE
         DATA(K)=(XDATA(K)*CONST+ADD)*10.**NSCALE
      ENDIF
C      
 120  CONTINUE
C
D     WRITE(KFILDO,125)(DATA(K),K=1,NVAL)
D125  FORMAT(/,' IN SCALX2',/,(15F8.2))
C
      RETURN
      END
