      PROGRAM EQNEVAL5
C$$$  MAIN PROGRAM DOCUMENTATION BLOCK  ***
C
C MAIN PROGRAM: ENS_EQNEVAL5
C   PRGMMR: WIEDENFELD      ORG: OST21       DATE: 2007-10-25
C
C ABSTRACT: DRIVER FOR PROGRAM U905.  SEE U905 COMMENTS OR PROGRAM
C           WRITEUP FOR VARIABLE DEFINITIONS.  AN ATTEMPT HAS BEEN
C           MADE TO INCLUDE ALL INFORMATION IN THIS DRIVER THAT
C           THE USER OF U905 MIGHT HAVE TO CHANGE.
C
C PROGRAM HISTORY LOG:
C   07-10-25  WIEDENFELD              -CREATED
C
C USAGE:
C
C        DATA SET USE
C        INPUT FILES:
C             PARM    - STANDARD IN
C
C        OUTPUT FILES: 
C             FORT.06 - STANDARD OUT
C
C        VARIABLES
C        LET ND1  = MAXIMUM NUMBER OF STATIONS THAT CAN BE DEALT WITH.
C                   MUST ALSO BE GE BLOCK. 
C            ND2  = MAXIMUM NUMBER OF TERMS IN AN EQUATION.
C            ND3  = MAXIMUM NUMBER OF PREDICTANDS PER EQUATION SET.
C            ND5  = MAXIMUM NUMBER OF STATION CALL LETTERS ON
C                   THE INPUT FILES.  MUST BE GE THE LARGEST RECORD
C                   ON THE INPUT INTERPOLATED FILE(S).  MUST ALSO
C                   BE GE ND1.
C            ND6  = MAXIMUM NUMBER OF INPUT DATA SETS THAT
C                   CAN BE DEALT WITH. 
C            ND7  = DIMENSION OF IS0( ), IS1( ), IS2( ), AND IS4( ).
C                   NOT ALL LOCATIONS ARE USED.  MAXIMUM SIZE IS FOR
C                   IS1( ) = 22 PLUS 32 CHARACTERS (ONE CHARACTER PER
C                   WORD) OF PLAIN TEXT = 54.
C            ND8  = MAXIMUM NUMBER OF DATES THAT CAN BE DEALT WITH.
C            ND9  = MAXIMUM NUMBER OF FIELDS STORED IN LSTORE( , ).
C            ND10 = THE MEMORY IN WORDS ALLOCATED TO THE SAVING OF
C                   PACKED DATA IN CORE( ).  WHEN THIS
C                   SPACE IS EXHAUSTED, SCRATCH DISK WILL BE USED.
C            ND11 = MAXIMUM NUMBER OF FILES FROM WHICH TO READ
C                   EQUATIONS, ONE SET AT A TIME. 6/2000 - MUST BE
C                   AT LEAST 5.
C            ND13 = MAXIMUM NUMBER OF DIFFERENT EQUATIONS PER SET.
C                   THIS WOULD BE = ND1 FOR SINGLE STATION EQUATIONS
C                   OR THE NUMBER OF REGIONS FOR REGIONAL EQUATIONS.
C        THEN IT IS SUFFICIENT THAT THE DIMENSIONS OF VARIABLES BE
C        AS INDICATED BELOW IN THIS EXAMPLE DIRVER.  NOTE THAT THE
C        VARIABLE L3264B IS SET TO 32 FOR A 32-BIT MACHINE AND TO
C        64 FOR A 64-BIT MACHINE.  L3264W AND NBLOCK WILL
C        AUTOMATICALLY ADJUST ACCORDINGLY.
C
C        SUBPROGRAMS CALLED: 
C             UNIQUE: - FCST90,RDST9,SETJDT,U905
C
C          LIBRARY:
C            W3LIB    - 
C            MDLLIB90 - 
C
C        EXIT STATES:
C          COND =    0 - SUCCESSFUL RUN
C
C REMARKS:  
C
C ATTRIBUTES:
C   LANGUAGE: FORTRAN 90 (XLF90 compiler)
C   MACHINE:  IBM SP
C
C$$$
C
      PARAMETER (L3264B=32)
      PARAMETER (L3264W=64/L3264B)
      PARAMETER (NBLOCK=6400/L3264B)
      PARAMETER (ND1=MAX(NBLOCK,15000))
      PARAMETER (ND2=20)
      PARAMETER (ND3=20)
      PARAMETER (ND4=1000)
      PARAMETER (ND5=MAX(ND1,30))
      PARAMETER (ND6=100)
      PARAMETER (ND7=54)
      PARAMETER (ND8=1000)
      PARAMETER (ND9=100000)
      PARAMETER (ND10=400000)
      PARAMETER (ND11=ND6)
      PARAMETER (ND13=3000)
C
      CHARACTER*8 CCALL(ND1,6),
     1            CCALLD(ND5)
      CHARACTER*20 NAME(ND1)
      CHARACTER*32 PLAIN(ND3),
     1             PLNSD(ND3)
      CHARACTER*60 NAMIN(ND6),EQNNAM(ND11)
C
      REAL*8 X(ND2+1,ND2+1,ND13)
C
      DIMENSION ICALL(L3264W,ND1,6),ISDATA(ND1),SDATA(ND1),XDATA(ND1)
      DIMENSION IPACK(ND5),ICALLD(L3264W,ND5),
     1          IWORK(ND5),DATA(ND5)
      DIMENSION KFILIN(ND6),MODNUM(ND6),JFOPEN(ND6)
      DIMENSION INDEXC(ND1,ND6)
      DIMENSION IS0(ND7),IS1(ND7),IS2(ND7),IS4(ND7)
      DIMENSION IDATE(ND8),NWORK(ND8)
      DIMENSION LSTORE(12,ND9)
      DIMENSION CORE(ND10)
      DIMENSION KFILEQ(ND11)
      DIMENSION NGP(ND13),LGP(ND13),MTRMS(ND13)
      DIMENSION ID(7,ND13,ND2),IDPARS(15,ND13,ND2),TRESHL(ND13,ND2),
     1          JD(4,ND13,ND2),ITAU(ND13,ND2),IUSED(ND13,ND2)
      DIMENSION CONST(ND13,ND3),
     1          AVG(ND13,ND3),
     2          CORR(ND13,ND3),
     3          ESS(ND13,ND3)
      DIMENSION COEF(ND13,ND2,ND3)
      DIMENSION ISCALD(ND3),ISCLSD(ND3),ICAT(ND3)
      DIMENSION IDTAND(4,ND3),IDTPAR(15,ND3),
     1          IDTNSD(4,ND3),IDPRSD(15,ND3)
      DIMENSION IPLAIN(L3264W,4,ND3),
     1          IPLNSD(L3264W,4,ND3)
      DIMENSION LOCSTA(ND1)
      DIMENSION FCST(ND1,ND3)
      DIMENSION VECTOR(ND1,ND13,ND2)
C
      EQUIVALENCE (ICALL,CCALL)
      EQUIVALENCE (ICALLD,CCALLD)
      EQUIVALENCE (PLAIN,IPLAIN)
      EQUIVALENCE (PLNSD,IPLNSD)
C
      DATA KFILDI/5/,
     1     KFILDO/6/
      DATA PLAIN/ND3*' '/ 
C
      CALL W3TAGB('ENS_EQNEVAL',2007,0247,0066,'OST21')
      CALL TIMPR(KFILDO,KFILDO,'START U905          ')
C
      CALL U905(KFILDI,KFILDO,KFILEQ,EQNNAM,
     1          ICALL,CCALL,ISDATA,SDATA,XDATA,NAME,ND1,
     3          ISCALD,IPLAIN,PLAIN,L3264B,L3264W,
     4          ICALLD,CCALLD,IPACK,DATA,IWORK,ND5,
     5          KFILIN,MODNUM,NAMIN,JFOPEN,
     6          INDEXC,ND6,
     7          IS0,IS1,IS2,IS4,ND7,
     8          IDATE,NWORK,ND8,
     9          LSTORE,ND9,
     A          ID,IDPARS,TRESHL,JD,ITAU,IUSED,
     B          CONST,AVG,ESS,CORR,COEF,X,VECTOR,
     C          IDTAND,IDTPAR,
     D          IDTNSD,IDPRSD,PLNSD,IPLNSD,ISCLSD,
     E          NGP,LGP,MTRMS,ICAT,LOCSTA,FCST,
     F          ND2,ND3,ND11,ND13,
     G          CORE,ND10,NBLOCK)
C
C
      CALL TIMPR(KFILDO,KFILDO,'END U905            ')
      CALL W3TAGE('ENS_EQNEVAL')
      STOP 
      END
