      SUBROUTINE RESTRW(KFILDO,XDATA,WHOLD,LTAG,LTAGWH,NSTA,IER)
C
C        JUNE      2005   GLAHN   TDL   MOS-2000
C        NOBEMBER  2007   GLAHN   MODIFIED PURPOSE 
C
C        PURPOSE
C            TO RESTORE THE DATA WITHHELD BY WITHOL1 IN U405A.
C
C        DATA SET USE
C            KFILDO   - UNIT NUMBER OF OUTPUT (PRINT) FILE.  (OUTPUT)
C
C        VARIABLES
C              KFILDO = UNIT NUMBER OF OUTPUT (PRINT) FILE.  (INPUT)
C            XDATA(K) = ON INPUT, HOLDS THE DATA ANALYZED (K=1,NSTA).
C                       ON OUTPUT, HOLDS ALL THE DATA, INCLUDING THE
C                       WITHHELD DATA.  (INPUT/OUTPUT)
C            WHOLD(K) = ARRAY HOLDING DATA WITHHELD (K=1,NSTA).
C                       (INPUT).
C             LTAG(K) = DENOTES USE OF DATA IN DATA(K) FOR STATION K
C                       (K=1,NSTA).
C                       0 = USE DATA.
C                       1 = STATION OUTSIDE RADIUS OF INFLUENCE FOR
C                           AREA BEING ANALYZED OR MISSING DATUM.
C                       2 = STATION LOCATION UNKNOWN.
C                       (INPUT/OUTPUT)
C           LTAGWH(K) = THE VALUES OF THE WITHHELD STATIONS ARE SAVED
C                       IN LTAGWH( ) AND ARE RESTORED IN LTAG( ) 
C                       (K=1,NSTA).  (INPUT)
C                NSTA = NUMBER OF STATIONS OR LOCATIONS BEING DEALT
C                       WITH.  (INPUT)
C                 IER = 0 = GOOD RETURN.  (OUTPUT)
C        1         2         3         4         5         6         7 X
C
      DIMENSION XDATA(NSTA),WHOLD(NSTA),LTAG(NSTA),LTAGWH(NSTA)
C
      DO 150 K=1,NSTA
C
      IF(WHOLD(K).NE.-9999.)THEN
         XDATA(K)=WHOLD(K)
         LTAG(K)=LTAGWH(K)
CD        WRITE(KFILDO,110)K,XDATA(K),LTAG(K)
CD110     FORMAT(' AT 110 IN RESTRW--K,XDATA(K),LTAG(K)',I7,F7.2,I4)
      ENDIF
C
 150  CONTINUE
C
      RETURN
      END

