         PROGRAM GRIBTOMDLPK
C
C$$$  MAIN PROGRAM DOCUMENTATION BLOCK
C
C MAIN PROGRAM: GRIBTOMDLPK 
C   PRGMMR: RUDACK                    ORG: OST21       DATE: 2003-06-01
C
C ABSTRACT: DRIVER FOR PROGRAM U130.  SEE U130 COMMENTS OR PROGRAM
C           WRITEUP FOR VARIABLE DEFINITIONS.  AN ATTEMPT HAS BEEN
C           MADE TO INCLUDE ALL INFORMATION IN THIS DRIVER THAT
C           THE USER OF U130 MIGHT HAVE TO CHANGE.  THE OPEN TO
C           THE CONTROL FILE 'U130.CN' IS HERE SO THAT ACCESS TO THE
C           CONTROL FILE CAN BE MODIFIED FOR IBM OR HP BATCH JOBS.
C
C PROGRAM HISTORY LOG:
C    JUNE       2003   RUDACK   MDL   MOS-2000
C    SEPTEMBER  2005   RUDACK   MODIFIED CODE TO MEET
C                               OPERATIONAL REQUIREMENTS. 
C    NOVEMBER   2007   WIEDENFELD FINISHED OPERATIONAL REQUIREMENTS.
C
C USAGE:
C
C DATA SET USE:
C    INPUT FILE:
C       FORT.KFILDI    - UNIT NUMBER OF DEFAULT INPUT FILE.
C                        THIS IS PROBABLY SPECIFIED FOR THE SYSTEM
C                        BEING USED.  SET IN DATA STATEMENT.
C    OUTPUT FILE:
C       FORT.KFILDO    - UNIT NUMBER OF DEFAULT OUTPUT (PRINT) FILE.
C                        THIS IS PROBABLY SPECIFIED FOR THE SYSTEM
C                        BEING USED.  SET IN DATA STATEMENT.
C
C PARAMETERS:
C           LET L3264B = INTEGER WORD LENGTH IN BITS OF MACHINE BEING
C                        USED (EITHER 32 OR 64).  
C                  ND4 = NUMBER OF CONSTANT VARIABLES IN THE VARIABLE 
C                        LIST. SINCE U130 IS DESIGNED TO USE ONLY ONE 
C                        CONSTANT VARIABLE, ND4 SHOULD BE SET TO A VALUE 
C                        OF ONE.     
C                  ND5 = DIMENSION OF IPACK( ), IWORK( ) AND DATA( ).  
C                        SINCE IT CANNOT BE KNOWN THE SIZE OF EACH 
C                        RECORD BEFORE READING IT, ND5 SHOULD BE AT 
C                        LEAST AS LARGE AS THE GRID DIMENSION 
C                        (I.E., NX*NY) OF THE DATA ON THE GRIB FILE.  
C                  ND6 = MAXIMUM NUMBER OF INPUT FILES THAT CAN BE DEALT 
C                        WITH IN ONE RUN.   
C                  ND7 = DIMENSION OF IS0( ), IS1( ), IS2( ), AND IS4( ).
C                        SHOULD BE GE 54.
C                  ND8 = MAXIMUM NUMBER OF DATES THAT CAN BE DEALT WITH IN ONE
C                        RUN.
C                  ND9 = MAXIMUM NUMBER OF RECORDS THAT ARE ANTICIPATED TO BE 
C                        ON A PARTICULAR GRIB FILE.
C                 ND10 = MAXIMUM NUMBER OF ELEMENTS THAT CAN BE PROCESSED IN 
C                        THE ELEMENT LIST FILE.  
C
C        THEN IT IS SUFFICIENT THAT THE DIMENSIONS OF VARIABLES BE
C        AS INDICATED BELOW IN THIS EXAMPLE DIRVER.  NOTE THAT THE
C        VARIABLE L3264B IS SET TO 32 FOR A 32-BIT MACHINE AND TO
C        64 FOR A 64-BIT MACHINE.  
C EXIT STATES:
C   COND =   0 - SUCCESSFUL RUN
C
C REMARKS:  REMOVED THE OPEN STATEMENT FOR THE U130.CN FILE.
C
C ATTRIBUTES:
C   LANGUAGE: FORTRAN 90 (xlf90 compiler)
C   MACHINE:  IBM SP
C
C   SUBROUTINES CALLED:
C      UNIQUE: U130, W3TAGB, W2TAGE
C      LIBRARIES:  g2_4lib w3_4lib mdl_4lib bacio_4lib
C                  jasperlib pnglib zlib moslib
C$$$
      PARAMETER (L3264B=32)
      PARAMETER (ND4=1)
      PARAMETER (ND5=800000)
      PARAMETER (ND6=50)
      PARAMETER (ND7=54)
      PARAMETER (ND8=1400)
      PARAMETER (ND9=60000)
      PARAMETER (ND10=10000)
C
      CHARACTER*12 UNITS(ND4)
      CHARACTER*32 PLAIN(ND4)
      CHARACTER*60 NAMIN(ND6),NAMIX(ND6)
C
      DIMENSION ISCALD(ND4),SMULT(ND4),SADD(ND4),
     1          ORIGIN(ND4),CINT(ND4),THRESH(ND4)
      DIMENSION ID(4,ND4),JD(4,ND4),IDPARS(15,ND4),JP(3,ND4)
      DIMENSION IPACK(ND5),IWORK(ND5),DATA(ND5)
      DIMENSION KFILIN(ND6),MODNUM(ND6),JFOPEN(ND6)
      DIMENSION IS0(ND7),IS1(ND7),IS2(ND7),IS4(ND7)
      DIMENSION IDATE(ND8),NWORK(ND8)
      DIMENSION LDATES(ND9)
C
      DATA KFILDI/5/,
     1     KFILDO/6/
C
      DATA PLAIN/ND4*' '/ 
C
      CALL W3TAGB('GRIBTOMDLPK',2000,0258,0065,'W/OST21')
      CALL TIMPR(KFILDO,KFILDO,'START GRIBTOMDLPK          ')
C
      CALL U130(KFILDI,KFILDO,ID,IDPARS,JD,JP,
     1          PLAIN,ISCALD,SMULT,SADD,ORIGIN,
     2          CINT,UNITS,THRESH,ND4,
     3          IPACK,IWORK,DATA,ND5,
     4          JFOPEN,MODNUM,KFILIN,NAMIN,KFILIX,
     5          NAMIX,ND6,IS0,IS1,IS2,IS4,ND7,
     6          IDATE,NWORK,ND8,LDATES,ND9,ND10,L3264B)
C
      CALL TIMPR(KFILDO,KFILDO,'END GRIBTOMDLPK            ')
      CALL W3TAGE('GRIBTOMDLPK')
      STOP 
C
      END
