      SUBROUTINE OPTION_GRIDARCH(KFILDO,KFIL10,NFIRST,
     1                  ID,IDPARS,THRESH,JD,NDATE,
     2                  KFILRA,RACESS,NUMRA,ICALL,CCALL,ICALLD,
     3                  CCALLD,NAME,NELEV,STALAT,STALON,
     4                  ITIMEZ,ISDATA,SDATA,SDATA1,L1DATA,DIR,ND1,NSTA,
     5                  NGRIDC,NGRID,ND11,NSLAB,IPACK,IWORK,DATA,ND5,
     6                  LSTORE,ND9,LITEMS,CORE,ND10,LASTL,
     7                  NBLOCK,LASTD,NSTORE,NFETCH,
     8                  IS0,IS1,IS2,IS4,ND7,
     9                  FD1,FD2,FD3,FD4,FD5,FD6,FD7,
     A                  FDVERT,FDTIME,FDSINS,FDMS,ND2X3,IP12,IP16,
     B                  ISTAV,L3264B,L3264W,MISTOT,IER)
C 
C        FEBRUARY  1995   GLAHN   TDL   MOS-2000 
C        AUGUST    1996   GLAHN   ADDED MISTOT
C        OCTOBER   1996   GLAHN   CHANGED 1-D AND 2-D IDENTIFIERS
C        OCTOBER   1996   GLAHN   WIND IDS FROM 004011 AND 004111
C                                 TO 004101 AND 004110
C        NOVEMBER  1996   GLAHN   ADDED KFILRA, RACESS, NUMRA, ICALLD
C        DECEMBER  1996   GLAHN   ADDED SUBROUTINE COMBIN 
C        JUNE      1997   GLAHN   D COMPILE OPTION COMMENTED OUT
C                                 DIAGNOSTIC CHANGE AT 198, 199
C        JANUARY   1998   GLAHN   ADDED SUBSTITUTE STATIONS IN CCALL( , )
C        MAY       1998   GLAHN   ADDED ITIMEZ( );
C                                 IER=99 CHANGED TO IER=-1
C        SEPTEMBER 1998   GLAHN   ISTAV( ) CHANGED TO = 1 FOR IER = -1
C        OCTOBER   1998   GLAHN   ELIMINATED DIAGNOSTIC FOR CCC = 799
C        OCTOBER   1998   GLAHN   CHANGED CALL TO CONST
C        NOVEMBER  1998   GLAHN   CHANGED DIMENSIONS OF CCALLD( )
C                                 AND ICALLD( , ) FROM ND1 TO ND5;
C                                 ELIMINATED ISDATA( ) IN CALL TO CONST
C        NOVEMBER  1998   GLAHN   ADDED DIR2UV TO CALL
C        DECEMBER  1998   GLAHN   ADDED DATE TO DIAGNOSTIC; IER=120
C                                 FROM CONST TREATED DIFFERENTLY
C        JANUARY   1999   GLAHN   CHANGES TO IER CODES AND DIAGNOSTICS
C                                 IDS FOR WSPEED AND EOWND TAKEN FROM SFANOS
C        JANUARY   1999   SFANOS  ADDED COMMENTS AND CALLS TO THE 
C                                 FOLLOWING SUBROUTINES:
C                                 POTEMP,MIXRAT,SPECHUM,MEANRH,DEWPT,
C                                 WETBULBT,LCL,DPTDPR,TPCP3,TPCP6,TPCP12,
C                                 TPCP24,NONCNVP,MDIV,WINDDR,KINDEX,
C                                 TTOTALS,SWEATI,DIR2UV,OBSDMAXT,OBSDMINT,
C                                 PCPX6,SVRVEC,KINXRF,OBSTCLD,OBSCIGHT
C        APRIL     1999   SFANOS  ADDED COMMENTS AND CALLS TO THE 
C                                 FOLLOWING SUBROUTINES:
C                                 OBSPTYPE, OBSTCLD, SFCTCLD, CORDP, SNOWFL
C        AUGUST    1999   GLAHN   ADDED IP12 TO CALL
C        MAY       2000   DREWRY  COMMENTED OUT CALLS TO SVRVEC.F, KINXRF.F,
C                                 RHVV.F, AND THETAE.F, IN ORDER TO RUN
C                                 U201 WITH THE SUBROUTINES CURRENTLY EXISTING
C                                 IN THE OPERATIONAL U201 LIBRARY ON THE IBM 
C        JUNE      2000   ALLEN   ADDED COMMENTS AND CALLS TO: FRZLVL, SSR,
C                                 ZRPRED, OBSTWET, OBSPRWXBIN.  UNCOMMENTED
C                                 CALL TO RHVV. 
C        JUNE      2000   ALLEN   ADDED CALLS TO VORTADV, AND TMPADV
C        JULY      2000   DALLAVALLE   ADDED CALLS TO OBSPOPO, OBSPOPO3,
C                                      AND OBSPOPC.
C        AUGUST    2000   DALLAVALLE   ADDED CALL TO LINDEX; UNCOMMENTED
C                                      CALLS TO KINXRF, SVRVEC, THETAE
C        SEPTEMBER 2000   MCE     COMMENTED OUT CALL TO OBSPOPO3 - ROUTINE
C                                 IS NOT WORKING YET.
C        SEPTEMBER 2000   ALLEN   ADDED CALL TO QADV, ADJUSTED CALL TO OBSTWET
C        SEPTEMBER 2000   DALLAVALLE   CORRECTED CALL TO KINXRF AND SVRVEC.
C        SEPTEMBER 2000   DALLAVALLE   ADDED CALL TO OBSOBVIS, CORRECTED CALL
C                                      TO OBSDPTD.
C        NOVEMBER  2000   GLAHN   CORRECTED SPELLING IN COMMENTS
C        JUNE      2001   DALLAVALLE   ADDED CALLS TO OBSMRPTYPE AND
C                                      OBSMRCLD
C        FEBRUARY  2002   GLAHN   CHANGED ND12 TO NUMRA IN ONE COMMENT
C        JULY      2002   RLC     UNCOMMENTED CALL TO OBSPOPO3, ADDED CALLS 
C	  			  TO SWTXRF, PBLMIX, AND MODELMXMN.  ADDED
C                                 CALL TO SATLEVRH, BUT LEFT IT COMMENTED OUT
C                                 TILL CONSTG IS ADDED TO U201
C          AUG     2002   SFANOS  CHANGED CALLS TO TPCP3, TPCP6, TPCP12; THEY
C                                 HAD NONCNVP IDS IN THEM; CHANGED NONCNVP -
C                                 OLDER VERSION IN LIBRARY
C        AUGUST    2002   RLC     UNCOMMENTED & CHANGED CALL TO SATLEVRH
C	OCTOBER    2002   CARROLL ADDED EXPERIMENTAL CODES TEMPCORR, DEWPCORR
C			          AND THKCORR.  THEY ARE COMMENTED OUT FOR
C				  POSSIBLE LATER USE.
C       OCTOBER    2002   WEISS   ARGUMENT LIST CHANGE TO SATLEVRH
C	OCTOBER    2002   CARROLL CHANGED CALL TO PCPX6 (FOR JCM).
C       NOVEMBER   2002   MCALOON LIBRARY WEEK - UPDATE TO INCLUDE CALLS FROM
C                                 DALLAVALLE 06/2001
C       NOVEMBER   2002   MCALOON LIBRARY WEEK - ADDED CALL TO OBSMRWSP FROM 
C                                 ERICKSON VERSION
C       JANUARY    2003   GLAHN/WEISS   ADDED NGRID AND NAME( ) TO CALL;
C                                       MODIFIED CALL TO CONST AND OTHERS
C                                 NOTE: ORIGINALLY FOR VERSION U204
C       FEBRUARY   2003   WEISS   ANOTHER ARGUMENT LIST CHANGE TO SATLEVRH
C                                 ADDED CALLS TO TSLOP AND UPSLOP. ALSO 
C                                 ADDED A SPECIAL CALL TO CONST FOR WHEN ONLY
C                                 TERRAIN HEIGHT IS REQUESTED AS A PREDICTOR.
C       FEBRUARY   2003   WEISS   CHANGED CALL TO CONST TO CONST1. 
C       JUNE       2003   RLC     ALLOWED FOR TWO VERSIONS OF TPCP24.  _OLD
C                                 IS THE OLD VERSION WITH THE INCORRECT
C                                 ALGORITHM.  IT STILL HAS THE ORIGINAL IDS.
C                                 TPCP24 IS THE CORRECT VERSION AND HAS NEW
C                                 IDS.  TPCP24_OLD CAN BE REMOVED ONCE ALL
C                                 QPF AND TSVR EQNS ARE REDEVELOPED.
C       JULY       2003   RLC     ALLOWED FOR TWO VERSIONS OF FRZLVL AND ZRPRED.
C                                 _OLD ARE THE OLD VERSIONS WITH THE INCORRECT
C                                 ALGORITHMS.  THEY STILL HAVE THE ORIGINAL IDS.
C                                 FRZLVL AND ZRPRED ARE THE CORRECT VERSIONS  
C                                 AND HAVE NEW IDS.  THE _OLD VERSIONS CAN BE 
C                                 REMOVED ONCE ALL PTYPE EQNS ARE REDEVELOPED.
C       JULY       2003   RLC     ADDED CALLS FOR SNOW PREDICTOR AND PREDICTAND
C                                 ROUTINES.
C       SEPTEMBER  2003   RLC     CHANGED CALL TO SSR TO MATCH NEW VERSION.
C       NOVEMBER   2003   RLC     ADDED CALL TO SATLEVNUM
C       JANUARY    2004   RLC     ADDED FD5 TO CALL TO WETBULBT AND NEW FFF TO
C                                 SPECHUM AND DEWPT FOR ETA32 WORK.
C       APRIL      2004   CMM     ADDED CALL TO RHNSPD FOR VISOBVIS.
C       APRIL      2004   RLC     MODIFIED CALL TO ZRPRED
C       OCTOBER    2004   RLC     ADDED CALLS TO ADTEMP AND LAPSER
C       MARCH      2005   JOE     ADDED CALL TO FTOKGRD
C       MARCH      2005   RLC     CHANGED CALL TO FTOKGRD,  ADDED CALLS TO
C                                 CHKTMPDP AND SHFTMXMN.
C       MARCH      2005   RLC     ADDED CALL TO WINDSP.
C       MARCH      2005   RLC     ADDED CALL TO ADJTMP.  THIS IS THE CORRECTED
C                                 VERSION OF ADTEMP.  ADTEMP WILL EVENTUALLY BE
C                                 REMOVED, BUT FOR NOW SOMETHING MIGHT BE USING IT.
C       AUGUST     2005   JOE     MODIFIED FROM OPTION IN MDLLIB.  CLEARED OUT ALL
C                                 CALLS EXCEPT CONST1
C       AUGUST     2005   JOE     PASSING ID IN PLACE OF JD IN CONST1.  JD HAS
C                                 BINARIES AND THRESHOLDS REMOVED WHICH PREVENTS
C                                 CONSTG FROM READING GRIDDED POPS.
C
C        PURPOSE 
C            TO CALL VARIOUS COMPUTATIONAL ROUTINES FOR PRED21 AND PRED22.
C            MOST COMPUTATIONAL ROUTINES, WHEN NEEDING THEMSELVES A
C            COMPUTED VARIABLE, WILL CALL OPTN2 RATHER THAN RECALLING
C            OPTION.  HOWEVER, WHEN THE LINEARIZATION ROUTINES L1D OR L2D
C            NEED A COMPUTED VARIABLE, THEY WILL CALL OPTION (A REENTRY).
C            IN THIS CASE, THE COMPUTATION MUST NOT INVOLVE ANOTHER CALL TO
C            L1D OR L2D.  THE CALLING SEQUENCE TO A ROUTINE LIKE L1D OR 
C            VERTP CONTAINS ALL THE VARIABLES NEEDED FOR REENTRY TO OPTION
C            OR ENTRY TO OPTN2; MORE SPECIFIC ROUTINES LIKE VORTH WILL
C            NOT NEED ALL OF THESE VARIABLES.  IT IS ASSUMED ANY
C            SECONDARY MISSING VALUES HAVE BEEN REMOVED.
C
C        DATA SET USE 
C            KFILDO - DEFAULT UNIT NUMBER FOR OUTPUT (PRINT) FILE.  (OUTPUT) 
C            KFIL10 - UNIT NUMBER OF TDL MOS-2000 FILE SYSTEM ACCESS.
C                     (INPUT/OUTPUT) 
C 
C        VARIABLES 
C              KFILDO = DEFAULT UNIT NUMBER FOR OUTPUT (PRINT) FILE. (INPUT) 
C              KFIL10 = UNIT NUMBER OF TDL MOS-2000 FILE SYSTEM ACCESS.
C                       (INPUT)
C              NFIRST = 1 FOR THE 1ST DATE.
C               ID(J) = THE PREDICTOR ID (J=1,4).  (INPUT)
C           IDPARS(J) = THE PARSED, INDIVIDUAL COMPONENTS OF THE PREDICTOR
C                       ID CORRESPONDING TO ID( ) (J=1,15).  (INPUT)
C                       J=1--CCC (CLASS OF VARIABLE),
C                       J=2--FFF (SUBCLASS OF VARIABLE),
C                       J=3--B (BINARY INDICATOR),
C                       J=4--DD (DATA SOURCE, MODEL NUMBER),
C                       J=5--V (VERTICAL APPLICATION),
C                       J=6--LBLBLBLB (BOTTOM OF LAYER, 0 IF ONLY 1 LAYER),
C                       J=7--LTLTLTLT (TOP OF LAYER),
C                       J=8--T (TRANSFORMATION),
C                       J=9--RR (RUN TIME OFFSET, ALWAYS + AND BACK IN TIME),
C                       J=10--OT (TIME APPLICATION),
C                       J=11--OH (TIME PERIOD IN HOURS),
C                       J=12--TAU (PROJECTION IN HOURS),
C                       J=13--I (INTERPOLATION TYPE),
C                       J=14--S (SMOOTHING INDICATOR), AND
C                       J=15--G (GRID INDICATOR).
C              THRESH = THE BINARY THRESHOLD ASSOCIATED WITH IDPARS( ).
C                       (INPUT)
C               JD(J) = THE BASIC INTEGER PREDICTOR ID (J=1,4).
C                       THIS IS THE SAME AS ID(J), EXCEPT THAT THE PORTIONS
C                       PERTAINING TO PROCESSING ARE OMITTED:
C                       B = IDPARS(3),
C                       T = IDPARS(8),
C                       I = IDPARS(13),
C                       S = IDPARS(14),
C                       G = IDPARS(15), AND
C                       THRESH.
C                       JD( ) IS USED TO IDENTIFY THE BASIC MODEL FIELDS
C                       AS READ FROM THE ARCHIVE.  (INPUT)
C               NDATE = THE DATE/TIME FOR WHICH PREDICTOR IS NEEDED.  (INPUT)
C           KFILRA(J) = HOLDS THE UNIT NUMBERS FOR ACCESSING THE MOS-2000
C                       EXTERNAL RANDOM ACCESS FILES (J=1,NUMRA).  (INPUT)
C           RACESS(J) = THE FILE NAMES CORRESPONDING TO KFILRA(J) (J=1,NUMRA).
C                       (CHARACTER*60)  (INPUT)
C               NUMRA = THE NUMBER OF UNIT NUMBERS AND NAMES IN KFILRA( )
C                       AND RACESS( ).  (INPUT)
C        ICALL(L,K,J) = 8 STATION CALL LETTERS AS CHARACTERS IN AN INTEGER
C                       VARIABLE (L=1,L3264W) (K=1,ND5) (J=1,6).
C                       EQUIVALENCED TO CCALL( , )  (INPUT/OUTPUT)
C          CCALL(K,J) = 8-CHARACTER STATION CALL LETTERS (OR GRIDPOINT
C                       LOCATIONS FOR GRID DEVELOPMENT) TO PROVIDE
C                       OUTPUT FOR (J=1) AND 5 POSSIBLE OTHER STATION
C                       CALL LETTERS (J=2,6) THAT CAN BE USED INSTEAD
C                       IF THE PRIMARY (J=1) STATION CANNOT BE FOUND 
C                       IN AN INPUT DIRECTORY (K=1,NSTA).  ALL STATION
C                       DATA ARE KEYED TO THIS LIST, EXCEPT POSSIBLY 
C                       CCALLD( ).  EQUIVALENCED TO ICALL( , ).
C                       (CHARACTER*8)  (INPUT/OUTPUT)
C         ICALLD(L,K) = 8 STATION CALL LETTERS AS CHARACTERS IN AN INTEGER
C                       VARIABLE (L=1,L3264W) (K=1,ND5).
C                       EQUIVALENCED TO CCALLD( ).  (INTERNAL)
C           CCALLD(K) = 8 STATION CALL LETTERS (K=1,ND5).  THIS LIST IS USED 
C                       IN L1D1 TO READ THE REGION LISTS.  (CHARACTER*8)
C                       (INTERNAL)
C             NAME(K) = NAMES OF STATIONS (K=1,NSTA).  USED FOR PRINTOUT
C                       ONLY.  (CHARACTER*20)  (INPUT)
C            NELEV(K) = ELEVATION OF STATIONS (K=1,NSTA).  (INPUT)
C           STALAT(K) = LATITUDE OF STATIONS (K=1,NSTA).  (INPUT)
C           STALON(K) = LONGITUDE OF STATIONS (K=1,NSTA).  (INPUT)
C           ITIMEZ(K) = TIME ZONE INDICATOR.  THE NUMBER OF HOURS
C                       THE STATION IS DIFFERENT FROM UTC (K=1,NSTA).
C                       (INPUT)
C           ISDATA(K) = WORK ARRAY (K=1,ND1).  (INTERNAL)
C            SDATA(K) = INTERPOLATED DATA TO RETURN, WHEN STATION DATA ARE
C                       BEING GENERATED (K=1,NSTA).  (OUTPUT)
C           SDATA1(K) = WORK ARRAY RESERVED FOR USE IN L2D2 (K=1,NSTA).
C                       (INTERNAL)
C           L1DATA(K) = THE ARRAY RESERVED FOR USE BY LINEARIZATION
C                       ROUTINES (K=1,NSTA).  (INTERNAL)
C          DIR(K,J,M) = THE IX (J=1) AND JY (J=2) POSITIONS ON THE GRID
C                       FOR THE COMBINATION OF GRID CHARACTERISTICS M
C                       (M=1,NGRID) AND STATION K (K=1,NSTA) IN NGRIDC( ,M).
C                       (INPUT)
C                 ND1 = MAXIMUM NUMBER OF STATIONS THAT CAN BE DEALT WITH.
C                       FIRST DIMENSION OF DIR( , , ).  (INPUT)
C                NSTA = NUMBER OF STATIONS OR LOCATIONS BEING DEALT WITH.
C                       (INPUT)
C         NGRIDC(L,M) = HOLDS THE GRID CHARACTERISTICS (L=1,6) FOR EACH GRID
C                       COMBINATION (M=1,NGRID).
C                       L=1--MAP PROJECTION NUMBER (3=LAMBERT, 5=POLAR
C                            STEREOGRAPHIC). 
C                       L=2--GRID LENGTH IN MILLIMETERS,
C                       L=3--LATITUDE AT WHICH GRID LENGTH IS CORRECT *10000,
C                       L=4--GRID ORIENTATION IN DEGREES *10000,
C                       L=5--LATITUDE OF LL CORNER IN DEGREES *10000,
C                       L=6--LONGITUDE OF LL CORNER IN DEGREES *10000.
C               NGRID = THE NUMBER OF GRID COMBINATIONS IN DIR( , , ),
C                       MAXIMUM OF ND11.  (INPUT)
C                ND11 = MAXIMUM NUMBER OF GRID COMBINATIONS THAT CAN BE
C                       DEALT WITH ON THIS RUN.  LAST DIMENSION OF
C                       NGRIDC( , ) AND DIR( , , ).  (INPUT)
C               NSLAB = THE NUMBER OF THE SLAB IN DIR( , , ) AND
C                       IN NGRIDC( , ) DEFINING THE CHARACTERISTICS
C                       OF THIS GRID.  SEE LSTORE(10, ).  FOR THE
C                       COMPUTATION ROUTINES RETURNING A GRID, THIS
C                       VALUE MUST BE OUTPUT BY GFETCH.  (OUTPUT) 
C            IPACK(J) = WORK ARRAY (J=1,ND5).  (INTERNAL)
C            IWORK(J) = WORK ARRAY (J=1,ND5).  (INTERNAL)
C             DATA(J) = ARRAY TO HOLD RETURNED DATA WHEN THE DATA ARE
C                       AT GRIDPOINTS. (J=1,ND5).  (OUTPUT)
C                 ND5 = DIMENSION OF IPACK( ), IWORK( ), AND DATA( ).
C                       (INPUT)
C         LSTORE(L,J) = THE ARRAY HOLDING INFORMATION ABOUT THE DATA 
C                       STORED (L=1,12) (J=1,LITEMS).  (INPUT/OUTPUT)
C                       L=1,4--THE 4 ID'S FOR THE DATA.
C                       L=5  --LOCATION OF STORED DATA.  WHEN IN CORE,
C                              THIS IS THE LOCATION IN CORE( ) WHERE
C                              THE DATA START.  WHEN ON DISK, 
C                              THIS IS MINUS THE RECORD NUMBER WHERE 
C                              THE DATA START.
C                       L=6  --THE NUMBER OF 4-BYTE WORDS STORED.
C                       L=7  --2 FOR DATA PACKED IN TDL GRIB, 1 FOR NOT.
C                       L=8  --THE DATE/TIME OF THE DATA IN FORMAT
C                              YYYYMMDDHH.
C                       L=9  --NUMBER OF TIMES DATA HAVE BEEN RETRIEVED.
C                       L=10 --NUMBER OF THE SLAB IN DIR( , ,L) AND
C                              IN NGRIDC( ,L) DEFINING THE CHARACTERISTICS
C                              OF THIS GRID.
C                       L=11 --THE NUMBER OF THE PREDICTOR IN THE SORTED
C                              LIST IN ID( ,N) (N=1,NPRED) FOR WHICH THIS
C                              VARIABLE IS NEEDED, WHEN IT IS NEEDED ONLY
C                              ONCE FROM LSTORE( , ).  WHEN IT IS NEEDED
C                              MORE THAN ONCE, THE VALUE IS SET = 7777.
C                       L=12 --USED INITIALLY IN ESTABLISHING MOSTORE( , ).
C                              LATER USED AS A WAY OF DETERMINING WHETHER
C                              TO KEEP THIS VARIABLE.
C                 ND9 = THE SECOND DIMENSION OF LSTORE( , ).  (INPUT)
C              LITEMS = THE NUMBER OF ITEMS (COLUMNS) IN LSTORE( , ) THAT 
C                       HAVE BEEN USED IN THIS RUN.  (INPUT/OUTPUT)
C             CORE(J) = THE ARRAY TO STORE OR RETRIEVE THE DATA IDENTIFIED IN
C                       LSTORE( , ) (J=1,ND10).  WHEN CORE( ) IS FULL
C                       DATA ARE STORED ON DISK.  (INPUT/OUTPUT)
C                ND10 = DIMENSION OF CORE( ).  (INPUT)
C               LASTL = THE LAST LOCATION IN CORE( ) USED FOR MOS-2000 INTERNAL
C                       STORAGE.  INITIALIZED TO 0 ON FIRST ENTRY TO GSTORE.
C                       ALSO INITIALIZED IN U201 IN CASE GSTORE IS NOT ENTERED.
C                       MUST BE CARRIED WHENEVER GSTORE IS TO BE CALLED.
C                       (INPUT/OUTPUT)
C              NBLOCK = THE BLOCK SIZE IN WORDS OF THE MOS-2000 RANDOM
C                       DISK FILE.  (INPUT)
C               LASTD = TOTAL NUMBER OF PHYSICAL RECORDS ON DISK FOR MOS-2000
C                       INTERNAL STORAGE.  MUST BE CARRIED WHENEVER GSTORE
C                       IS TO BE CALLED.  (INPUT)
C              NSTORE = THE NUMBER OF TIMES GSTORE HAS BEEN ENTERED.  GSTORE
C                       KEEPS TRACK OF THIS AND RETURNS THE VALUE.  (OUTPUT)
C              NFETCH = THE NUMBER OF TIMES GFETCH HAS BEEN ENTERED.  GFETCH
C                       KEEPS TRACK OF THIS AND RETURNS THE VALUE.  (OUTPUT)
C              IS0(J) = MOS-2000 GRIB SECTION 0 ID'S (J=1,3).  (INTERNAL)
C              IS1(J) = MOS-2000 GRIB SECTION 1 ID'S (J=1,22+).  (INTERNAL)
C              IS2(J) = MOS-2000 GRIB SECTION 2 ID'S (J=1,12).  (INTERNAL)
C              IS4(J) = MOS-2000 GRIB SECTION 4 ID'S (J=1,4).  (INTERNAL)
C                 ND7 = DIMENSION OF IS0( ), IS1( ), IS2( ), AND IS4( ).
C                       NOT ALL LOCATIONS ARE USED.  (INPUT)
C  FD1(J),FD2(J), ETC = WORK ARRAYS (J=1,ND2X3).  THESE MAY BE USED IN
C                       ROUTINES AS 2-DIMENSIONAL ARRAYS, WHERE THE
C                       TOTAL ARRAY SIZE IS ND2*ND3=ND2X3 AS DECLARED IN
C                       THE CALLING PROGRAM.  (INTERNAL)
C           FDVERT(J) = TEMPORARY STORAGE RESERVED FOR SUBROUTINE VERTP
C                       (J=1,ND2X3).  (INTERNAL)
C           FDTIME(J) = TEMPORARY STORAGE RESERVED FOR SUBROUTINE TEMEP
C                       (J=1,ND2X3).  (INTERNAL)
C       FDSINS(IX,JY) = USED TO SAVE THE SIN OF THE LATITUDE IN SUBROUTINE
C                       PSMAPF (IX=1,NX) (JY=1,NY).  THE USER MUST NOT
C                       USE THIS ARRAY EXCEPT IN CALLING PSMAPF.
C                       (INPUT/OUTPUT)
C         FDMS(IX,JY) = USED TO SAVE THE MAP FACTOR IN SUBROUTINE
C                       PSMAPF (IX=1,NX) (JY=1,NY).  THE USER MUST NOT
C                       USE THIS ARRAY EXCEPT IN CALLING PSMAPF.
C                       (INPUT/OUTPUT)
C               ND2X3 = DIMENSION OF FD1( ), FD2( ), ETC.  (INPUT)
C                IP12 = INDICATES WHETHER (>1) OR NOT (=0) THE LIST OF
C                       STATIONS ON THE INPUT VECTOR FILES WILL BE WRITTEN
C                       TO UNIT IP12.  (INPUT)
C                IP16 = DIAGNOSTICS FOR LINEARIZATION AND CONSTANT ROUTINES
C                       (E.G., STATIONS IN THRESHOLD LISTS THAT ARE NOT
C                       BEING DEALT WITH IN THIS RUN).  (INPUT)
C               ISTAV = 1 WHEN THE DATA RETURNED ARE STATION DATA.  
C                       0 WHEN THE DATA RETURNED ARE GRID DATA OR DATA
C                         ARE NOT AVAILABLE FOR RETURN.  (OUTPUT)
C              L3264B = INTEGER WORD LENGTH IN BITS OF MACHINE BEING USED
C                       (EITHER 32 OR 64).  (INPUT)
C              L3264W = NUMBER OF WORDS IN 64 BITS, EITHER 1 OR 2.  (INPUT)
C              MISTOT = TOTAL NUMBER OF TIMES A MISSING INDICATOR
C                       HAS BEEN ENCOUNTERED IN UNPACKING GRIDS.
C                       (INPUT/OUTPUT)
C                 IER = STATUS RETURN.
C                        0 = GOOD RETURN.
C                       -1 = PREDICTOR NOT DEFINED IN OPTION.
C                       SEE CALLED ROUTINES FOR OTHER VALUES.
C                       (INTERNAL-OUTPUT)
C
C        NONSYSTEM SUBROUTINES USED 
C            VERTP, TIMEP, VORTW, VORTH, WSPEED, EOWND, GWIND, DIVW,
C            FORIER, L1D, TESTS, POTEMP, MIXRAT, SPECHUM, MEANRH,
C            DEWPT, WETBULBT, LCL, DPTDPR, TPCP3, TPCP6, TPCP12, TPCP24,
C            NONCNVP, MDIV, WINDDR, KINDEX, TTOTALS, SWEATI, DIR2UV,
C            OBSDMAXT, OBSDMINT, PCPX6, SVRVEC, KINXRF, OBSTCLD, OBSCIGHT,
C            OBSPTYPE, OBSTCLD, SFCTCLD, CORDP, SNOWFL, RHVV, FRZLVL, SSR,
C            ZRPRED, OBSTWET, OBSPRWXBIN, VORTADV, TMPADV, QADV, OBSPOPC,
C            OBSPOPO, OBSPOPO3, LINDEX, OBSOBVIS, OBSDPTD, SWTXRF, PBLMIX,
C            SATLEVRH, MODELMXMN, OBSMRPTYPE, OBSMRCLD, OBSMRWSP, SNOWAMT,
C            OBSCPCPOS, OBSCPSNOW, OBSCPPRCP, SATLEVNUM, RHNSPD,ADTEMP,
C            LAPSER, FTOKGRD, CHKTMPDP, SHFTMXMN, WINDSP, ADJTMP
C
      CHARACTER*8 CCALL(ND1,6),
     1            CCALLD(ND5)
      CHARACTER*60 RACESS(NUMRA)
      CHARACTER*20 NAME(ND1)
C
      DIMENSION ICALL(L3264W,ND1,6),
     1          NELEV(ND1),STALAT(ND1),STALON(ND1),ITIMEZ(ND1),
     2          ISDATA(ND1),SDATA(ND1),SDATA1(ND1),L1DATA(ND1)
      DIMENSION DIR(ND1,2,ND11),NGRIDC(6,ND11)
      DIMENSION ID(4),IDPARS(15),JD(4)
      DIMENSION FD1(ND2X3),FD2(ND2X3),FD3(ND2X3),FD4(ND2X3),
     1          FD5(ND2X3),FD6(ND2X3),FD7(ND2X3),
     2          FDVERT(ND2X3),FDTIME(ND2X3),FDSINS(ND2X3),FDMS(ND2X3)
      DIMENSION IPACK(ND5),IWORK(ND5),DATA(ND5),ICALLD(L3264W,ND5)
      DIMENSION IS0(ND7),IS1(ND7),IS2(ND7),IS4(ND7)
      DIMENSION LSTORE(12,ND9)
      DIMENSION CORE(ND10)
      DIMENSION KFILRA(NUMRA)
C 
D     WRITE(KFILDO,100)(ID(J),J=1,4),(IDPARS(J),J=1,15)
D100  FORMAT(' *********** IN OPTION *************',/,' ',4I10,15I5)
C
      IER=0
C
C        LOOK FOR GRIDDED FORECAST DATA, TO BE PROVIDED IN
C        THE MOS-2000 EXTERNAL RANDOM ACCESS FILES.
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      IF(IDPARS(1).GE.200.AND.IDPARS(1).LE.299)THEN
C
C       PASS ID IN PLACE OF JD
C
CCC            CALL CONST1(KFILDO,KFIL10,IP12,
CCC     1                 ID,IDPARS,JD,NDATE,
            CALL CONST1(KFILDO,KFIL10,IP12,
     1                 ID,IDPARS,ID,NDATE,
     2                 KFILRA,RACESS,NUMRA,
     3                 CCALL,ICALLD,CCALLD,NAME,STALAT,STALON,
     4                 ISDATA,SDATA,DIR,ND1,NSTA,
     5                 NGRIDC,NGRID,ND11,NSLAB,
     6                 IPACK,IWORK,DATA,ND5,
     7                 LSTORE,ND9,LITEMS,CORE,ND10,LASTL,
     8                 NBLOCK,LASTD,NSTORE,NFETCH,
     9                 IS0,IS1,IS2,IS4,ND7,
     A                 ISTAV,L3264B,L3264W,IER)
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C        LOOK FOR CONSTANT DATA, TO BE PROVIDED IN
C        THE MOS-2000 EXTERNAL RANDOM ACCESS FILES.
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      ELSEIF(IDPARS(1).GE.400.AND.IDPARS(1).LE.499)THEN
C
            CALL CONST1(KFILDO,KFIL10,IP12,
     1                 ID,IDPARS,JD,NDATE,
     2                 KFILRA,RACESS,NUMRA,
     3                 CCALL,ICALLD,CCALLD,NAME,STALAT,STALON,
     4                 ISDATA,SDATA,DIR,ND1,NSTA,
     5                 NGRIDC,NGRID,ND11,NSLAB,
     6                 IPACK,IWORK,DATA,ND5,
     7                 LSTORE,ND9,LITEMS,CORE,ND10,LASTL,
     8                 NBLOCK,LASTD,NSTORE,NFETCH,
     9                 IS0,IS1,IS2,IS4,ND7,
     A                 ISTAV,L3264B,L3264W,IER)
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
      ELSE
         IER=-3
C           IER SET -3 HERE TO DISTINGUISH IT FROM
C           IER = -2 FROM OPTN2 FROM A SUBROUTINE.
      ENDIF
C
      IF(IER.EQ.0)THEN
C           GOOD RETURN, GOOD DATA.
         GO TO 200
C
      ELSEIF(IER.EQ.47)THEN
C           ID IDENTIFIED, BUT DATA NOT AVAILABLE FROM
C           A SUBROUTINE.  OPTN2 WILL HAVE PRINTED
C           A DIAGNOSTIC ONLY IF THE ID COULD NOT BE FOUND.
         WRITE(KFILDO,199)(ID(J),J=1,4),NDATE,IER
         GO TO 200
C
      ELSEIF(IER.EQ.120)THEN
C           ID IDENTIFIED, GOOD DATA FROM CONST.  IER = 120
C           JUST MEANS SOME STATIONS COULD NOT BE FOUND IN 
C           THE CONSTANT FILE.
         GO TO 200
C
      ELSEIF(IER.EQ.-2)THEN
C           AT THIS POINT, IER = -2 IS FROM OPTN2 FROM A
C           SUBROUTINE.  THE ID WAS FOUND IN OPTION.  JUST
C           SET IER = 47 TO INDICATE MISSING DATA.  A
C           DIAGNOSTIC WAS PRINTED IN OPTN2, SO DON'T DO
C           ONE HERE.
         IER=47 
         GO TO 200
C
      ELSEIF(IER.EQ.-3)THEN
C           IER = -3 SHOULD MEAN THE ID WAS NOT FOUND IN OPTION.
C           SET IT TO -2.  (IT IS POSSIBLE THAT A SUBROUTINE
C           CALLED OPTION INSTEAD OF OPTN2 AND IER = -3 CAME
C           FROM THAT CALL.  IN THIS CASE, IER = -2 WILL
C           RESULT WHEN IT SHOULD HAVE BEEN 47.  THIS
C           SHOULD ONLY RESULT WHEN DATA WERE NOT AVAILABLE
C           FOR DAY 1.)  ONLY WHEN THE ID WAS NOT FOUND IN
C           OPTION IS ISTAV SET.
         IER=-2
         ISTAV=1
C
         IF(IDPARS(1).NE.799)THEN
C              IN CASE OPTION IS ENTERED WITH THE DUMMY
C              IDPARS(1) = 799, THE DIAGNOSTIC IS NOT PRINTED.
            WRITE(KFILDO,198)(ID(J),J=1,4),NDATE,IER
 198        FORMAT(/' ****VARIABLE NOT IDENTIFIED    ',
     1              I9.9,1X,I9.9,1X,I9.9,1X,I10.3,
     2              ' IN OPTION_GRIDARCH FOR DATE',I11,',  IER = ',I4)
         ENDIF
C
         GO TO 200
C
      ELSE
         WRITE(KFILDO,199)(ID(J),J=1,4),NDATE,IER
 199     FORMAT(/' ****TROUBLE COMPUTING VARIABLE ',
     1           I9.9,1X,I9.9,1X,I9.9,1X,I10.3,
     2           ' IN OPTION_GRIDARCH FOR DATE',I11,',  IER = ',I4)
C           ANY VALUE OF IER OTHER THAN THE ONES ABOVE
C           IS FROM A SUBROUTINE AND SHOULD BE RETAINED, 
C           ESPECIALLY -1 WHICH MEANS THE DATA SHOULD NOT
C           BE WRITTEN.
      ENDIF
C
 200  CONTINUE
C
D     WRITE(KFILDO,210)IER,(SDATA(J),J=1,6)
D210  FORMAT(/' RETURNING FROM OPTION_GRIDARCH, IER =',
D    +       I5/('     '10F10.2))
      RETURN
      END
