#!/bin/sh

########################################
# Generate EKDMOS Gempak files
########################################

date
export PS4=' $SECONDS + '
set -xa

####################################
# Specify NET Name and model
# model - model grib field to repack
####################################
export NET=ekd
export RUN=ekd

export DATA=${DATA:-${DATAROOT}/${jobid}}
mkdir -m 775 -p $DATA
cd $DATA
export cycle=${cycle:-t${cyc}z}

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export pgmout="OUTPUT.${jobid}"

####################################
# Specify EKDMOS version number
####################################
export EKDMOS_MODEL_VERSION=${EKDMOS_MODEL_VERSION:-${ekdmos_ver}}
export EKDMOS_CODE_VERSION=${EKDMOS_CODE_VERSION:-${ekdmos_shared_ver}}
export MOS_CODE_VERSION=${MOS_CODE_VERSION:-${mos_shared_ver}}

####################################
# Specify Execution Areas
####################################
export HOMEekd=${HOMEekd:-${NWROOT}/ekdmos.${EKDMOS_MODEL_VERSION}}
export HOMEcode=${HOMEcode:-${NWROOT}/ekdmos_shared.${EKDMOS_CODE_VERSION}}
export HOMEmdl=${HOMEmdl:-${NWROOT}/mos_shared.${MOS_CODE_VERSION}}
export FIXekd=${FIXekd:-$HOMEekd/fix}
export PARMekd=${PARMekd:-$HOMEekd/parm}
export EXECekd=${EXECekd:-$HOMEcode/exec}
export EXECmdl=${EXECmdl:-${HOMEmdl}/exec}
#
# Set up model and cycle specific variables
#
export GRIB=grib
export DBN_ALERT_TYPE=EKDMOS_GEMPAK

##############################
# Run setpdy and initialize PDY variables
##############################
setpdy.sh
. PDY

##############################################
# Define COM directories
##############################################
export COMIN=${COMIN:-${COMROOT}/${NET}/${envir}/$RUN.${PDY}}
export COMOUT=${COMOUT:-${COMROOT}/nawips/${envir}/$RUN.${PDY}}

mkdir -m 775 -p $COMOUT
 
env

cp ${NWROOTp1}/gempak/fix/ekdmos_g2varswmo2.tbl g2varswmo2.tbl

########################################################
# Launch the driver script.
${HOMEekd}/scripts/exekdmos_nawips.sh.ecf
########################################################

cat $pgmout

date

if [ "$KEEPDATA" != YES ]; then
   cd $DATAROOT
   rm -rf $DATA
fi 
