      SUBROUTINE L1D3(KFILDO,L1DATA,SDATA,ND1,NSTA,
     1                THRES,PROB,NTHRES,NREG,NOCAT,IER)
C
C        APRIL 1995   GLAHN   TDL   MOS-2000
C        JUNE  1997   GLAHN   D COMPILE OPTION COMMENTED OUT
C 
C        PURPOSE 
C            TO COMPUTE THE TRANSFORMED VARIABLE FOR L1D.
C
C        DATA SET USE 
C            KFILDO - UNIT NUMBER FOR OUTPUT (PRINT) FILE.  (OUTPUT)
C
C        VARIABLES 
C              KFILDO = UNIT NUMBER FOR OUTPUT (PRINT) FILE.  (INPUT)
C           L1DATA(J) = REGION INDEX LIST (J=1,ND1).  (INPUT)
C            SDATA(J) = ON INPUT, THE VARIABLE TO LINEARIZE; ON OUTPUT,
C                       THE LINEARIZED VARIABLE.  (INPUT-OUTPUT)
C                 ND1 = MAXIMUM NUMBER OF STATIONS THAT CAN BE DEALT WITH.
C                       DIMENSION OF L1DATA( ) AND SDATA( ).  (INPUT)
C                NSTA = NUMBER OF STATIONS OR LOCATIONS BEING DEALT WITH.
C                       (INPUT)
C          THRES(J,L) = THRESHOLDS (J=1,NOCAT) (L=1,NREG).  (INPUT)
C           PROB(J,L) = PROBABILITES (RELATIVE FREQUENCIES) ASSOCIATED WITH
C                       THE CATEGORY DEFINED BY GE THRES(J-1) AND LT THRES(J),
C                       WHERE THRES(0) IS ASSUMED TO BE LESS THAN ANY
C                       POSSIBLE VALUE (J=1,NOCAT) (L=1,NREG).  (INPUT)
C              NTHRES = NUMBER OF THRESHOLDS THAT CAN BE DEALT WITH IN THIS
C                       ROUTINE.  (INPUT)
C                NREG = NUMBER OF REGIONS THAT CAN BE DEALT WITH IN THIS
C                       ROUTINE.  (INPUT)
C               NOCAT = THE NUMBER OF CATEGORIES ACTUALLY BEING DEALT WITH
C                       IN THIS ROUTINE.  MUST BE LE NTHRES.  (INTERNAL)
C                 IER = STATUS RETURN.  (OUTPUT)
C                         0 = GOOD RETURN.
C                         
C        NON SYSTEM SUBROUTINES CALLED 
C            NONE.
C
      DIMENSION L1DATA(ND1),SDATA(ND1)
      DIMENSION THRES(NTHRES,NREG),PROB(NTHRES,NREG)
      
C        COMPUTE THE VARIABLE.
C
      IER=0
C
C***D     WRITE(KFILDO,109)((THRES(L,M),PROB(L,M),L=1,NTHRES),M=1,NREG)
C***D109  FORMAT(' THRES, PROB IN L1D3'/
C***D    1      (' '2F10.2))
C
      DO 270 J=1,NSTA
      LOC=L1DATA(J)
      IF(LOC.NE.0)GO TO 262
C        THIS STATION WAS NOT IN THE THRESHOLD LIST.
      SDATA(J)=9999.
      GO TO 270
C
 262  DO 265 L=1,NOCAT-1
C***D     WRITE(KFILDO,263)J,L,LOC,SDATA(J),THRES(L,LOC),PROB(L,LOC)
C***D263  FORMAT(' J,L,LOC,SDATA(J),THRES(L,LOC),PROB(L,LOC)'3I5,3F10.2)
      IF(SDATA(J).GT.THRES(L,LOC))GO TO 265
      SDATA(J)=PROB(L,LOC)
      GO TO 270
C
 265  CONTINUE
      SDATA(J)=PROB(NOCAT,LOC)
 270  CONTINUE
C
      RETURN
      END
