      SUBROUTINE ITDLP_STOP
C
C        HISTORY
C
C        MAY       2014   ENGLE       CREATED FOR ITDLP
C
C        PURPOSE
C
C            TO UNLINK THE INPUT FILE (IF IT WAS OPENED
C            AS A SYMLINK), THEN CLOSE ALL OPEN FILES
C            AND EXIT VIA FORTRAN INTRINSIC SUBROUTINE,
C            EXIT.
C
C        MODULES USED
C            ISO_C_BINDING, ITDLP_MOD
C
C        C FUNCTIONS CALLED (VIA FORTRAN INTERFACE)
C            UNLINK
C
      USE, INTRINSIC :: ISO_C_BINDING
      USE ITDLP_MOD
      IMPLICIT NONE
C
      IF(IS_SYMLINK) CALL UNLINK(TRIM(CSLINK)//C_NULL_CHAR)
      CALL EXIT()
C
      RETURN
      END SUBROUTINE ITDLP_STOP
